users:
    pattern:  /
    defaults: { _controller: "CompeteComBundle:Users:index" }

users_show:
    pattern:  /{id}/show
    defaults: { _controller: "CompeteComBundle:Users:show" }

users_new:
    pattern:  /new/{role}
    defaults: { _controller: "CompeteComBundle:Users:new" }

users_create:
    pattern:  /create/{role}
    defaults: { _controller: "CompeteComBundle:Users:create"}
    requirements: { _method: post }

users_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CompeteComBundle:Users:edit" }

users_update:
    pattern:  /{id}/update
    defaults: { _controller: "CompeteComBundle:Users:update" }
    requirements: { _method: post|put }

users_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CompeteComBundle:Users:delete" }
    requirements: { _method: post|delete }
