<?php

namespace Compete\ComBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ArtisticCompetitionsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Compete\ComBundle\Controller\ArtisticCompetitionsController();
        return $instance;
    }
}
