<?php

namespace Proxies\__CG__\Compete\ComBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Competitions extends \Compete\ComBundle\Entity\Competitions implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setStDate($stDate)
    {
        $this->__load();
        return parent::setStDate($stDate);
    }

    public function getStDate()
    {
        $this->__load();
        return parent::getStDate();
    }

    public function setEndDate($endDate)
    {
        $this->__load();
        return parent::setEndDate($endDate);
    }

    public function getEndDate()
    {
        $this->__load();
        return parent::getEndDate();
    }

    public function setWinner($winner)
    {
        $this->__load();
        return parent::setWinner($winner);
    }

    public function getWinner()
    {
        $this->__load();
        return parent::getWinner();
    }

    public function setGrade(\Compete\ComBundle\Entity\Grades $grade = NULL)
    {
        $this->__load();
        return parent::setGrade($grade);
    }

    public function getGrade()
    {
        $this->__load();
        return parent::getGrade();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'stDate', 'endDate', 'winner', 'grade');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}